# Copyright 2020 mrtska

TARGET_BOARD_PLATFORM := thinkpad

TARGET_NO_BOOTLOADER := true
TARGET_CPU_ABI := x86_64
TARGET_ARCH := x86_64
TARGET_ARCH_VARIANT := x86_64

TARGET_2ND_CPU_ABI := x86
TARGET_2ND_ARCH := x86
TARGET_2ND_ARCH_VARIANT := x86_64

TARGET_USES_64_BIT_BINDER := true

BOARD_MALLOC_ALIGNMENT := 16

TARGET_NO_KERNEL := false
#BOARD_KERNEL_CONFIG_FILE := /home/mrtska/kernel2/common/out/.config
#BOARD_KERNEL_VERSION := 4.19.160
BOARD_USES_ALSA_AUDIO ?= true
BUILD_WITH_ALSA_UTILS ?= true

#BOARD_USES_DRM_GRALLOC := true

#BOARD_USE_CUSTOMIZED_MESA := true
BUILD_BROKEN_USES_BUILD_HOST_STATIC_LIBRARY := true

# Don't build emulator.
BUILD_EMULATOR := false

USE_OPENGL_RENDERER := true
BOARD_GPU_DRIVERS := swrast vmwgfx i965 i915

# Use F2FS as user partition.
TARGET_USERIMAGES_USE_F2FS := true
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs

# 10GB / 2 10737418240
BOARD_USERDATAIMAGE_PARTITION_SIZE := 5368709120

TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product

# system.img
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4

TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true

BOARD_PROPERTY_OVERRIDES_SPLIT_ENABLED := true
BOARD_VNDK_VERSION := current

BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4

BOARD_USES_METADATA_PARTITION := true

# System as root.
TARGET_PRELINK_MODULE := false

# SELinux
BOARD_VENDOR_SEPOLICY_DIRS += device/mrtska/thinkpad-x1-yoga-gen5/sepolicy/nonplat 
BOARD_VENDOR_SEPOLICY_DIRS += device/mrtska/thinkpad-x1-yoga-gen5/sepolicy/plat_private

#BOARD_VENDOR_KERNEL_MODULES := $(wildcard /home/mrtska/kernel2/common/out/outm/*.ko)